### ISSUE TITLE
Agree Report Card Data Fields

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/cognicity-grasp#6]
Suggested fields:
- card_id
- created_at (ISO 8601 timestamp with timezone from user device)
- text (UTF8 @ 140 chars)
- water_depth
- image (optional)
- location (GeoJson (point))

**Comment by talltom** [comment]
Current database implementation of data fields: https://github.com/urbanriskmap/cognicity-grasp/blob/master/schema/schema.sql#L34

**Comment by MaanasaPriyaa** [comment]
Done. Closing it.
